# Gradle 设置
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# 环境设置
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# 模组信息
mod_id=eai_goety_patch
mod_name=EAI Goety Patch
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=eai_goety_patch
mod_authors=Arakiel
mod_description=Fixes NPE in EnhancedAI EAIData.has when entity/level is null.

# 依赖版本
enhancedai_version=3.3.7.3
insanelib_version=1.21.19
mobspropertiesrandomness_version=5.1.2.2